title: LoRa APRS Wiki
description: >
    The central documentation and knowledge base for LoRa APRS projects,
    including the Tracker, Digi/iGate and Mobile App.
baseurl: ""
url: "https://wiki.lora-aprs.pl"
github_username: SQ2CPA

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

markdown: kramdown
permalink: /:categories/:title/

defaults:
    - scope:
          path: ""
          type: "pages"
      values:
          layout: "default"

plugins:
    - jekyll-feed
    - jekyll-include-cache

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
