title: LoRa APRS Projects Wiki
description: >- # this means to ignore newlines until "baseurl:"
    The central documentation and knowledge base for LoRa APRS projects,
    including the Tracker, Digi/iGate, and Mobile App.
baseurl: "/LoRa_APRS_Wiki" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: SQ2CPA # Change this

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "air", "dark", "dirt", "neon", "mint", "sunrise", "dark" are other options

markdown: kramdown
permalink: /:categories/:title/

defaults:
    - scope:
          path: ""
          type: "pages"
      values:
          layout: "default"

plugins:
    - jekyll-feed
    - jekyll-include-cache

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
